
spring.application.name=studentapp

# 1. Local Database Connection
# Updated to use student_db
spring.datasource.url=jdbc:mysql://localhost:3306/student_db
spring.datasource.username=root
spring.datasource.password=Nithin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. Server Port
server.port=8080